["AppData/Roaming/bat/config"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/bat/config"
refreshPeriod = "24h"
["AppData/Roaming/bat/themes/Catppuccin%20Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/bat/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "24h"
