["AppData/Roaming/bat/config"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/bat/config"
refreshPeriod = "24h"

["AppData/Roaming/bat/themes/Catppuccin%20Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/bat/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "24h"

["AppData/Local/lazygit/config.yml"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/lazygit/config.yml"
refreshPeriod = "24h"

["AppData/Roaming/yazi/config/init.lua"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/yazi/init.lua"
refreshPeriod = "24h"

["AppData/Roaming/yazi/config/keymap.toml"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/yazi/keymap.toml"
refreshPeriod = "24h"

["AppData/Roaming/yazi/config/package.toml"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/yazi/package.toml"
refreshPeriod = "24h"

["AppData/Roaming/yazi/config/theme.toml"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/yazi/theme.toml"
refreshPeriod = "24h"

["AppData/Roaming/yazi/config/yazi.toml"]
type = "file"
url = "https://raw.githubusercontent.com/ninagrosse/dotfiles/refs/heads/main/dot_config/yazi/yazi.toml"
refreshPeriod = "24h"
