# C:\Users\<USER>\AppData\Roaming\alacritty\alacritty.toml

[general]
live_config_reload = true
import = [
  "~/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = "ubuntu2404"

[window]
dimensions = { columns = 140, lines = 40 }
# decorations = "None"
opacity = 0.95
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "p", mods = "Control|Shift", command = { program = "alacritty", args = ["-e", "powershell -NoExit -Command \"cd ~\""] } }
]
